export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const SET_FORUMS = 'SET_FORUMS'
export const SET_THREADS = 'SET_THREADS'
export const SET_THREAD = 'SET_THREAD'